development:
  adapter: postgresql
  encoding: utf8
  database: crowdshiba
  pool: 5
  username: ignaciopalladino
  password:
  host: localhost
test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: myapp
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: myapp_production
  pool: 5
  username: myapp
  password:
